name: floras tests conda env - MacOS
on:
  push:
  pull_request:

jobs:
  create-env:
    name: Testing conda env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.10","3.11","3.12"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          miniconda-version: "latest"
          auto-activate-base: false

      - name: Install pygraphviz conda
        run: conda install --channel conda-forge pygraphviz

      - name: Check conda
        run: |
            conda info
            conda list

      - name: Add pdm
        run: pip install pdm

      - name: Install package
        run: pdm install

      - name: Try to use cached Spot
        id: cache-spot
        uses: actions/cache@v4
        with:
            path: spot-2.12
            key: ${{ runner.os }}-${{ matrix.python-version }}-spot-${{ hashFiles('get_spot.py') }}-${{ hashFiles('pyproject.toml') }}
      - name: Install Spot
        if: steps.cache-spot.outputs.cache-hit == 'true'
        run: |
          cd spot-2.12
          make install
      - name: Build and install Spot
        if: steps.cache-spot.outputs.cache-hit != 'true'
        run: |
          pdm run python get_spot.py

      - name : Install Package for Testing
        run : conda install pytest

      - name : Run tests
        run : pdm run pytest -v tests
